module.exports = {
  // HTTP Status Codes
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  MOVED_PERMANENTLY: 301,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  CONFLICT: 409,
  PRECONDITION_FAILED: 412,
  REQUEST_TOO_LONG: 413,
  REQUEST_URI_TOO_LONG: 414,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,

  INVALID_CREDENTIALS: 'Invalid credentials!',
  UNAUTHORIZE_ERROR: 'Unauthorized!',
  CATCH_ERROR: 'Something went wrong',
  VALIDATION_ERROR: 'Validation Error! Please check your inputs',
  USER_LOGIN: 'User login successfully',
  EMAIL_NO_FOUND: 'Email does not exist!',
  USER_NOT_ACTIVE: 'Your profile is not verify or active',
  USER_NOT_FOUND: 'User not found!',
  SESSION_EXPIRED: 'Session expired. Please re-login!',
  RECORDS_FOUND: 'Records fetched successfully',
  ADMIN_ACCESS: 'Only Admin can access!',
  NO_RECORD_FOUND: 'No record found!',
  DUPLICATE_ERROR: 'Already exist!',
  RECORD_CREATED: 'Record created successfully',
  RECORD_UPDATED: 'Record updated successfully',
  RECORD_DELETED: 'Record deleted successfully',
  NOT_ACCESS: 'You have no permission to access!',
  RESET_PASSWORD_SUCCESS: 'Reset password mail sent successfully!',
  RESET_PASSWORD_LINK_EXPIRED:
    'Your password reset link has been expired, Please try again',
  RESET_PASSWORD_LINK_INVALID: 'Invalid reset password link',
  PASSWORD_RESET_SUCCESS: 'Your password has been reset successfully!',
  REQUIRED_FIELD: 'Need to provide at least one field',
  USER_ID_REQUIRED: 'User id is required!',

  // Activation Email Messages
  ACTIVATION_EMAIL_SENT: 'Activation email sent successfully!',
  ACTIVATION_LINK_EXPIRED: 'Your activation link has expired. Please request a new one.',
  ACTIVATION_LINK_INVALID: 'Invalid activation link',
  ACCOUNT_ACTIVATED: 'Your account has been activated successfully!',
  ACCOUNT_ALREADY_ACTIVATED: 'Your account is already activated',

  // User Roles
  USER_ROLE: {
    SUPER_ADMIN: 'Super Admin',
    PROJECT_MANAGER: 'Project Manager',
    TECHNICIAN: 'Technician',
    API: 'API',
  },

  ADMIN: 'Admin',
  TECHNICIAN: 'Technician',
  PROJECT_MANAGER: 'Project Manager',
};